---
- hosts: all
  tasks:
  - name: This is a terrible playbook that I want codebot to fix
    debug:
      msg: "go-go-codebot! Fix my issues"
    when: t

  - debug: "This is also a terrible piece of code running on {{ ansible_hostname }}"