---
- hosts: all
  tasks:
  - name: This is a terrible playbook that I want codebot to fix
    debug:
      msg: go-go-codebot! Fix my issues
    when: t

  - debug: This is also a terrible piece of code running on {{ ansible_hostname }}

  - name: And one more really bad task
    ansible.builtin.shell: "cp -rv /home/admin/test-file /tmp/test-file.txt"  ## this copies a file in a terrible way, hopefully codebot does something?



